{
	"version": 1607593729,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/boule01-sheet0.png",
		"images/boule02-sheet0.png",
		"images/boule03-sheet0.png",
		"images/boule04-sheet0.png",
		"images/boule05-sheet0.png",
		"images/boule06-sheet0.png",
		"images/boule07-sheet0.png",
		"images/boule08-sheet0.png",
		"images/boule11-sheet0.png",
		"images/boule10-sheet0.png",
		"images/boule09-sheet0.png",
		"images/boule12-sheet0.png",
		"images/boule19-sheet0.png",
		"images/boule15-sheet0.png",
		"images/boule14-sheet0.png",
		"images/boule18-sheet0.png",
		"images/boule22-sheet0.png",
		"images/boule21-sheet0.png",
		"images/boule16-sheet0.png",
		"images/boule23-sheet0.png",
		"images/boule17-sheet0.png",
		"images/boule20-sheet0.png",
		"images/boule24-sheet0.png",
		"images/boule13-sheet0.png",
		"images/case01-sheet0.png",
		"images/case02-sheet0.png",
		"images/case03-sheet0.png",
		"images/case04-sheet0.png",
		"images/case05-sheet0.png",
		"images/case06-sheet0.png",
		"images/case07-sheet0.png",
		"images/case08-sheet0.png",
		"images/case10-sheet0.png",
		"images/case09-sheet0.png",
		"images/case11-sheet0.png",
		"images/case13-sheet0.png",
		"images/case12-sheet0.png",
		"images/case14-sheet0.png",
		"images/case15-sheet0.png",
		"images/case20-sheet0.png",
		"images/case17-sheet0.png",
		"images/case18-sheet0.png",
		"images/case19-sheet0.png",
		"images/case16-sheet0.png",
		"images/case22-sheet0.png",
		"images/case24-sheet0.png",
		"images/case21-sheet0.png",
		"images/case23-sheet0.png",
		"images/zoomboule01-sheet0.png",
		"images/sapin-sheet0.png",
		"images/Étoile-sheet0.png",
		"images/lumières-sheet0.png",
		"images/lumières-sheet1.png",
		"media/ring 1.m4a",
		"media/ring 1.ogg",
		"media/ring 2.m4a",
		"media/ring 2.ogg",
		"media/ring 3.m4a",
		"media/ring 3.ogg",
		"media/ring 4.m4a",
		"media/ring 4.ogg",
		"media/merry christmas.m4a",
		"media/merry christmas.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}